server:
  port: 9000
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_list
    username: root
    password: susheel@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.app.keycloak.server-url}/realms/${spring.app.keycloak.realm}

  app:
    keycloak:
      admin:
        client-id: admin-cli
        client-secret: 3UnvxE6g9NTxVSsTDjxzbOOJJyXLWCRL
      realm: To-Do-List
      server-url: http://localhost:9192

